name: Feature Request
description: Request a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for using Rivet! We appreciate your feedback.
  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: Describe your new feature request?
      placeholder: Rivet should do this!
      value: "..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Ironclad/rivet)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
